// src/app/router/routeTree.gen.ts
// Auto-generated by TanStack Router CLI
// This file will be overwritten by the CLI

// src/app/router/routeTree.gen.ts
// Manual TanStack Router route tree for feature-based structure
import { createRootRoute, createRoute } from '@tanstack/react-router';

// Root route with layout and error boundary
import { RootLayout, RootErrorBoundary } from '../layouts/RootLayout';
export const rootRoute = createRootRoute({
  component: RootLayout,
  errorComponent: RootErrorBoundary,
});

// Users domain routes
export const usersIndexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: 'users',
  component: () => import('../../features/users/routes/index.route').then((m) => m.default),
});
export const userDetailRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: 'users/:userId',
  component: () => import('../../features/users/routes/$userId.route').then((m) => m.default),
});

// Auth domain routes
export const loginRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: 'auth/login',
  component: () => import('../../features/auth/routes/login.route').then((m) => m.default),
});
export const registerRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: 'auth/register',
  component: () => import('../../features/auth/routes/register.route').then((m) => m.default),
});

// Compose the route tree
export const routeTree = rootRoute.addChildren([
  usersIndexRoute,
  userDetailRoute,
  loginRoute,
  registerRoute,
]);
